Error 2021-01-24 03:52:37: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/sting/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/sting/.config/Code/User/settings.json')
	at _handleError (/home/sting/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async m.readFile (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:832552)
	at async g.fixSettingsFile (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:288845)
	at async Promise.all (index 0)
	at async g.updateSettings (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:290565)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2021-01-24 03:52:37: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/sting/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/sting/.vscode/settings.json')
	at _handleError (/home/sting/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async m.readFile (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:832552)
	at async g.fixSettingsFile (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:288845)
	at async Promise.all (index 1)
	at async g.updateSettings (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:290565)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-24 03:54:16: Find kernel spec, Class name = I, completed in 17113ms, has a falsy return value, Arg 1: <Uri:/home/sting/ARIP2-PRJ3/AA.ipynb>, Arg 2: {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":3},"orig_nbformat":2}, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: DataScience Error [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: DataScience Error [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
Error 2021-01-24 03:54:16: Failed to initialize ipywidgetHandler [Error: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at I.installDependenciesIntoInterpreter (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209125)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:207810)]
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-24 03:56:43: Jupyter Kernel Spec not found for a local connection
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.5 64-bit
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-01-24 03:59:55: Kernel died [r [Error]: [IPKernelApp] ERROR | Exception in message handler:

	at t._next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:439:21)] 
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-24 04:01:57: Jupyter Kernel Spec not found for a local connection
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.5 64-bit
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-01-24 04:03:17: Kernel died [r [Error]: [IPKernelApp] ERROR | Exception in message handler:

	at t._next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:439:21)] 
Error 2021-01-24 04:06:03: Failed to load notebook file file:///home/sting/Untitled-1.ipynb [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/sting/Untitled-1.ipynb' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/sting/Untitled-1.ipynb')
	at _handleError (/home/sting/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async m.readFile (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:832552)
	at async r.loadFromFile (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:180454)
	at async T.loadModel (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:613437)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-24 04:06:11: Jupyter Kernel Spec not found for a local connection
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.5 64-bit
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-24 04:06:46: Jupyter Kernel Spec not found for a local connection
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.5 64-bit
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-01-24 04:07:08: Kernel died [r [Error]: [IPKernelApp] ERROR | Exception in message handler:

	at t._next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/home/sting/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:439:21)] 
Error 2021-01-24 04:39:49: Disposing session as kernel process died ExitCode: undefined, Reason: undefined
